# Process the results of the Cicero E-P run.
rm(list=ls())
library(rtracklayer)
library(GenomicRanges)
library(Seurat)
library(SeuratWrappers)

inDir <- "/home/rstudio/isilon/private/projects/FetalHindbrain/Sarropoulos2026/260406_CiceroRLonly"
CPG_DMR_FILE <- "/home/rstudio/isilon/private/projects/FetalHindbrain/EMseq_FETHB3/output/downstream/EMseq_FETHB2-FETHB3/CpG/DMRs/CTsnv_excluded/withoutBatchCorrection/240711/DMRs.csv"
geneFile <-  "/home/rstudio/isilon/private/projects/FetalHindbrain/anno/gencode.v44.basic.annotation.gtf"

# Processed RNA and ATAC files for mid-gestation samples.
# Files generated by Sarropoulous_ATAC.R code.
atacFile <- "/home/rstudio/isilon/private/projects/FetalHindbrain/Sarropoulos2026/260402/Sarropoulos_ATAC_Seurat.rds"
rnaFile <- "/home/rstudio/isilon/private/projects/FetalHindbrain/Sarropoulos2026/260402/Sarropoulos_RNA_Seurat.rds"

outDir <- "/home/rstudio/isilon/private/projects/FetalHindbrain/Sarropoulos2026"
outDir <- sprintf("%s/%s_DMR_overlap_EPs", outDir, format(Sys.Date(),"%y%m%d"))
if (!file.exists(outDir)) dir.create(outDir, recursive = FALSE)

logFile <- sprintf("%s/%s_Sarropoulos_Cicero_DMR_overlap.log", outDir, format(Sys.Date(),"%y%m%d"))
sink(logFile, split = TRUE)

tryCatch({
cat("Reading Cicero results for rhombic lip cells\n")
fName <- sprintf("%s/ciceroRLOnly_passCutoff.Rdata", inDir)
load(fName)
conns <- cicero.good; rm(cicero.good)

cat(sprintf("Total %s connections\n", prettyNum(nrow(conns), big.mark = ",")))

# create a data.frame of TSS sites of genes
gene.gr <- import(geneFile, format="gtf")
gene.gr <- subset(gene.gr, gene_type == "protein_coding" & type == "transcript")
tss.gr <- promoters(gene.gr, upstream=0, downstream=1)
tss.df <- data.frame(
    "chr" = seqnames(tss.gr),
    "start" = start(tss.gr),
    "end" = end(tss.gr),
    "gene_id" = tss.gr$gene_id,
    "gene_name" = tss.gr$gene_name
)
tss.df <- tss.df[!duplicated(tss.df$gene_id),]
colnames(tss.df)[5] <- "gene"
cat(sprintf("Created TSS data.frame with %s unique genes\n", prettyNum(nrow(tss.df), big.mark = ",")))

# compute overlap of each of the peaks in the Cicero connections with the TSS sites, and annotate the peaks with gene names.
tmp <- do.call("rbind", strsplit(conns$Peak1, split="-"))
gr1 <- makeGRangesFromDataFrame(data.frame(
    "chr" = tmp[,1],
    "start" = as.numeric(tmp[,2]),
    "end" = as.numeric(tmp[,3])
))
tmp <- do.call("rbind", strsplit(as.character(conns$Peak2), split="-"))
gr2 <- makeGRangesFromDataFrame(data.frame(
    "chr" = tmp[,1],
    "start" = as.numeric(tmp[,2]),
    "end" = as.numeric(tmp[,3])
))
ov1 <- findOverlaps(gr1, tss.gr)
ov2 <- findOverlaps(gr2, tss.gr)
conns$gene1 <- NA
conns$gene2 <- NA
conns$gene1[queryHits(ov1)] <- tss.gr$gene_name[subjectHits(ov1)]
conns$gene2[queryHits(ov2)] <- tss.gr$gene_name[subjectHits(ov2)]
cat(sprintf("Annotated %i peaks with gene names\n", sum(!is.na(conns$gene1)) + sum(!is.na(conns$gene2))))

# annotate the GRanges with gene names.
gr1$gene <- conns$gene1
gr2$gene <- conns$gene2

# annotate ATAC peaks with gene names.
cat("reading Sarropoulos ATAC Seurat object\n")
t0 <- Sys.time()
srat <- readRDS(atacFile)
print(Sys.time()-t0)
cat(sprintf("Sarropoulos ATAC: %i cells, %i features\n", ncol(srat), nrow(srat)))

Idents(srat) <- srat$rna_precisest_label
cat("* Finding marker peaks for the RL progenitor cluster...\n")
da_peaks <- FindMarkers(
  object = srat,
  ident.1 = "progenitor_RL",
  ident.2 = NULL,
  min.pct = 0.1,
  test.use = 'wilcox'
)
cat(sprintf("Total peaks = %s; Q < 0.1 = %s\n", 
    prettyNum(nrow(da_peaks), big.mark = ","), 
    prettyNum(sum(da_peaks$p_val_adj < 0.1), big.mark = ","))
)
open_peaks <- rownames(da_peaks)[da_peaks$p_val_adj < 0.1 & da_peaks$avg_log2FC > 0]
cat(sprintf("Total %s peaks open in RL progenitors\n", 
    prettyNum(length(open_peaks), big.mark = ",")))

cat("-----------------------------------\n")
cat("Getting genes upregulated in the rhombic lip\n")
cat("-----------------------------------\n")
# now get the genes upregulated in this file.
cat("Reading gene expression data\n")
rna <- readRDS(rnaFile)
DefaultAssay(rna) <- "SCT"
Idents(rna) <- rna$precisest_label
t0 <- Sys.time()
rl_markers <- FindMarkers(
  object = rna,
  ident.1 = "progenitor_RL",
  ident.2 = NULL,
  min.pct = 0.1,
  test.use = 'wilcox'
)
print(Sys.time()-t0)
cat(sprintf("Total genes tested for DEG = %s; Q < 0.1 = %s\n", 
    prettyNum(nrow(rl_markers), big.mark = ","), 
    prettyNum(sum(rl_markers$p_val_adj < 0.1), big.mark = ","))
)
upreg_genes <- rownames(rl_markers)[rl_markers$p_val_adj < 0.2 & rl_markers$avg_log2FC > 0]
cat(sprintf("Total %s genes upregulated in RL progenitors\n", 
    prettyNum(length(upreg_genes), big.mark = ",")))

# convert Ensembl IDs to HGNC symbols.
gene.gr <- import(geneFile, format="gtf")
gene.gr <- subset(gene.gr, gene_type == "protein_coding" & type == "gene")
gene.df <- data.frame(
    "chr" = seqnames(gene.gr),
    "start" = start(gene.gr),
    "end" = end(gene.gr),
    "gene_id" = gene.gr$gene_id,
    "gene_name" = gene.gr$gene_name
)
gene.df$gene_id <- gsub("\\..*", "", gene.df$gene_id) 
# convert the names of the upregulated genes from Ensembl IDs to HGNC symbols.
upreg_genes_hgnc <- na.omit(gene.df$gene_name[match(upreg_genes, gene.df$gene_id)])

upreg_gene_idx <- union(
    which(gr1$gene %in% upreg_genes_hgnc), 
    which(gr2$gene %in% upreg_genes_hgnc)
)
gr1.hiconf <- gr1[upreg_gene_idx]
gr2.hiconf <- gr2[upreg_gene_idx]
cat(sprintf("Total %s connections linked to upregulated genes\n", 
    prettyNum(length(upreg_gene_idx), big.mark = ",")))

###tmp <- strsplit(open_peaks, "-")
###df <- do.call("rbind", tmp)
###open_peak_GR <- GRanges(df[,1], IRanges(as.numeric(df[,2]), as.numeric(df[,3])))
###idx1 <- findOverlaps(gr1, open_peak_GR)
###idx1 <- queryHits(idx1)
###idx2 <- findOverlaps(gr2, open_peak_GR)
###idx2 <- queryHits(idx2)
###open_peak_idx <- intersect(idx1, idx2)
###cat(sprintf("Total %s connections linked to open peaks in RL progenitors\n", 
###    prettyNum(length(open_peak_idx), big.mark = ",")))

cat("-----------------------------------\n")
cat("Reading the rhombic lip DMRs now\n")
cat("-----------------------------------\n")
dmrs <- read.delim(CPG_DMR_FILE,sep="\t", header=TRUE)
dmr_GR <- GRanges(dmrs$chr, IRanges(dmrs$start, dmrs$end))

cat("Find overlaps with connections in general\n")
idx1 <- subjectHits(findOverlaps(gr1, dmr_GR))
idx2 <- subjectHits(findOverlaps(gr2, dmr_GR))
idx <- union(idx1, idx2)
cat(sprintf("Total %s DMRs linked to connections\n", prettyNum(length(idx), big.mark = ",")))

cat("Find overlap with connections associated with upregulated genes\n")
ol1 <-  findOverlaps(gr1.hiconf, dmr_GR)
df1.hiconf <- as.data.frame(gr1.hiconf[queryHits(ol1)])
dmr1 <- cbind(df1.hiconf, dmrs[subjectHits(ol1),])
dmr1 <- dmr1[!duplicated(dmr1),]

ol2 <- findOverlaps(gr2.hiconf, dmr_GR)
df2.hiconf <- as.data.frame(gr2.hiconf[queryHits(ol2)])
dmr2 <- cbind(df2.hiconf, dmrs[subjectHits(ol2),])
dmr2 <- dmr2[!duplicated(dmr2),]

dmr <- rbind(dmr1, dmr2)
dmr <- dmr[!duplicated(dmr),]
colnames(dmr)[1:6] <- paste0("ATAC_inferred_EP", colnames(dmr)[1:6])
colnames(dmr)[7:ncol(dmr)] <- paste0("DMR_", colnames(dmr)[7:ncol(dmr)])
write.csv(dmr, file=sprintf("%s/Sarropoulos_RL_DMR_overlap.csv", outDir), row.names=FALSE)  


browser()

}, error=function(ex){
    print(ex)
}, finally={
    sink(NULL)
})