# Process the results of the Cicero E-P run.
rm(list=ls())
library(rtracklayer)
library(GenomicRanges)
library(Seurat)
library(SeuratWrappers)
library(Biostrings)
library(memes)
library(BSgenome.Hsapiens.UCSC.hg38)
library(gprofiler2)

source("../FETHB2-FETHB3/utils_PaiLab.R")

inDir <- "/home/rstudio/isilon/private/projects/FetalHindbrain/Sarropoulos2026/260406_CiceroRLonly"
CPG_DMR_FILE <- "/home/rstudio/isilon/private/projects/FetalHindbrain/EMseq_FETHB3/output/downstream/EMseq_FETHB2-FETHB3/CpG/DMRs/CTsnv_excluded/withoutBatchCorrection/240711/DMRs.csv"
geneFile <-  "/home/rstudio/isilon/private/projects/FetalHindbrain/anno/gencode.v44.basic.annotation.gtf"

# Processed RNA and ATAC files for mid-gestation samples.
# Files generated by Sarropoulous_ATAC.R code.
atacFile <- "/home/rstudio/isilon/private/projects/FetalHindbrain/Sarropoulos2026/260402/Sarropoulos_ATAC_Seurat.rds"
rnaFile <- "/home/rstudio/isilon/private/projects/FetalHindbrain/Sarropoulos2026/260402/Sarropoulos_RNA_Seurat.rds"

tf_db <- "/home/rstudio/isilon/private/projects/FetalHindbrain/anno/meme/HOCOMOCOv12/filteredTFdb/Hendrikse2022_RL_activeGenes_TF.meme"
meme_path <- "/home/rstudio/software/meme/bin"
options(meme_bin = meme_path)

outDir <- "/home/rstudio/isilon/private/projects/FetalHindbrain/Sarropoulos2026"
outDir <- sprintf("%s/%s_DMR_overlap_EPs", outDir, format(Sys.Date(),"%y%m%d"))
if (!file.exists(outDir)) dir.create(outDir, recursive = FALSE)

logFile <- sprintf("%s/%s_Sarropoulos_Cicero_DMR_overlap.log", outDir, format(Sys.Date(),"%y%m%d"))
sink(logFile, split = TRUE)

tryCatch({
cat("Reading Cicero results for rhombic lip cells\n")
fName <- sprintf("%s/ciceroRLOnly_passCutoff.Rdata", inDir)
load(fName)
conns <- cicero.good; rm(cicero.good)

cat(sprintf("Total %s connections\n", prettyNum(nrow(conns), big.mark = ",")))

# create a data.frame of TSS sites of genes
gene.gr <- import(geneFile, format="gtf")
gene.gr <- subset(gene.gr, gene_type == "protein_coding" & type == "transcript")
tss.gr <- promoters(gene.gr, upstream=0, downstream=1)
tss.df <- data.frame(
    "chr" = seqnames(tss.gr),
    "start" = start(tss.gr),
    "end" = end(tss.gr),
    "gene_id" = tss.gr$gene_id,
    "gene_name" = tss.gr$gene_name
)
tss.df <- tss.df[!duplicated(tss.df$gene_id),]
colnames(tss.df)[5] <- "gene"
cat(sprintf("Created TSS data.frame with %s unique genes\n", prettyNum(nrow(tss.df), big.mark = ",")))

# compute overlap of each of the peaks in the Cicero connections with the TSS sites, and annotate the peaks with gene names.
tmp <- do.call("rbind", strsplit(conns$Peak1, split="-"))
gr1 <- makeGRangesFromDataFrame(data.frame(
    "chr" = tmp[,1],
    "start" = as.numeric(tmp[,2]),
    "end" = as.numeric(tmp[,3])
))
tmp <- do.call("rbind", strsplit(as.character(conns$Peak2), split="-"))
gr2 <- makeGRangesFromDataFrame(data.frame(
    "chr" = tmp[,1],
    "start" = as.numeric(tmp[,2]),
    "end" = as.numeric(tmp[,3])
))

conns$gene1 <- NA; conns$gene2 <- NA
ov1 <- findOverlaps(gr1, tss.gr)
conns$gene1[queryHits(ov1)] <- tss.gr$gene_name[subjectHits(ov1)]
ov2 <- findOverlaps(gr2, tss.gr)
conns$gene2[queryHits(ov2)] <- tss.gr$gene_name[subjectHits(ov2)]
cat(sprintf("Annotated %i peaks with gene names\n", 
    sum(!is.na(conns$gene1)) + sum(!is.na(conns$gene2))))

# annotate the GRanges with gene names.
gr1$gene <- conns$gene1
gr2$gene <- conns$gene2


cat("-----------------------------------\n")
cat("Getting genes upregulated in the rhombic lip\n")
cat("-----------------------------------\n")
# now get the genes upregulated in this file.
cat("Reading gene expression data\n")
rna <- readRDS(rnaFile)
DefaultAssay(rna) <- "SCT"
Idents(rna) <- rna$precisest_label
t0 <- Sys.time()
rl_markers <- FindMarkers(
  object = rna,
  ident.1 = "progenitor_RL",
  ident.2 = NULL,
  min.pct = 0.1,
  test.use = 'wilcox'
)
print(Sys.time()-t0)
cat(sprintf("Total genes tested for DEG = %s; Q < 0.1 = %s\n", 
    prettyNum(nrow(rl_markers), big.mark = ","), 
    prettyNum(sum(rl_markers$p_val_adj < 0.1), big.mark = ","))
)
upreg_genes <- rownames(rl_markers)[rl_markers$p_val_adj < 0.1 & rl_markers$avg_log2FC > 0]
cat(sprintf("Total %s genes upregulated in RL progenitors\n", 
    prettyNum(length(upreg_genes), big.mark = ",")))

# convert Ensembl IDs to HGNC symbols.
gene.gr <- import(geneFile, format="gtf")
gene.gr <- subset(gene.gr, gene_type == "protein_coding" & type == "gene")
gene.df <- data.frame(
    "chr" = seqnames(gene.gr),
    "start" = start(gene.gr),
    "end" = end(gene.gr),
    "gene_id" = gene.gr$gene_id,
    "gene_name" = gene.gr$gene_name
)
gene.df$gene_id <- gsub("\\..*", "", gene.df$gene_id) 
# convert the names of the upregulated genes from Ensembl IDs to HGNC symbols.
upreg_genes_hgnc <- na.omit(gene.df$gene_name[match(upreg_genes, gene.df$gene_id)])

upreg_gene_idx <- union(
    which(gr1$gene %in% upreg_genes_hgnc), 
    which(gr2$gene %in% upreg_genes_hgnc)
)
gr1.hiconf <- gr1[upreg_gene_idx]
gr2.hiconf <- gr2[upreg_gene_idx]
cat(sprintf("Total %s connections linked to upregulated genes\n", 
    prettyNum(length(upreg_gene_idx), big.mark = ",")))

cat("Filtering for connections with exactly one peak at a TSS\n")
idx1 <- which(!is.na(gr1.hiconf$gene) & is.na(gr2.hiconf$gene))
idx2 <- which(!is.na(gr2.hiconf$gene) & is.na(gr1.hiconf$gene))
idx <- union(idx1, idx2)
cat(sprintf("Total %s connections linked to upregulated genes with exactly one peak at a TSS\n", 
    prettyNum(length(idx), big.mark = ",")))

newDF <- cbind(as.data.frame(gr1.hiconf[idx]), as.data.frame(gr2.hiconf[idx]))
colnames(newDF)[6] <- "gene1"
colnames(newDF)[12] <- "gene2"
newDF$gene <- ifelse(!is.na(newDF$gene1), newDF$gene1, newDF$gene2)

# create a new table such that the enhancers (no TSS) are first, and the promoters (with TSS) 
# are second, and the gene names are in one column.
inferredEP <- NULL
idx <- which(is.na(newDF$gene1))
inferredEP <- newDF[idx, c(1:3, 7:9, 13)]
colnames(inferredEP)[7] <- "gene"
idx <- which(!is.na(newDF$gene1))
inferredEP <- rbind(inferredEP, newDF[idx, c(7:9, 1:3, 13)])
colnames(inferredEP) <- c("chr_enh", "start_enh", "end_enh", "chr_prom", "start_prom", "end_prom", "gene")
inferredEP <- inferredEP[!duplicated(inferredEP),]
cat(sprintf("Total %s inferred E-P connections with exactly one peak at a TSS\n", prettyNum(nrow(inferredEP), big.mark = ",")))
write.table(inferredEP, file=sprintf("%s/Sarropoulos_RL_Cicero_inferredEP_upregGenes_oneTSS.txt", outDir), sep="\t", 
    row.names=FALSE, quote=FALSE)

cat("-----------------------------------\n")
cat("Reading the rhombic lip DMRs now\n")
cat("-----------------------------------\n")
dmrs <- read.delim(CPG_DMR_FILE,sep="\t", header=TRUE)
dmr_GR <- GRanges(dmrs$chr, IRanges(dmrs$start, dmrs$end))

inferredEP_GR <- makeGRangesFromDataFrame(inferredEP, 
    seqnames.field="chr_enh", start.field="start_enh", end.field="end_enh")
ol <- findOverlaps(inferredEP_GR, dmr_GR)
cat(sprintf("Total %s DMRs linked to inferred E-P connections\n", 
    prettyNum(length(unique(subjectHits(ol))), big.mark = ",")))
cat(sprintf("DMRs linked to %i inferred enhancers targeting %i unique genes",
    length(unique(queryHits(ol))),
    length(unique(inferredEP$gene[queryHits(ol)]))
))

dmrDF <- cbind(
    as.data.frame(inferredEP[queryHits(ol),]), 
    dmrs[subjectHits(ol),]
)
colnames(dmrDF)[8:ncol(dmrDF)] <- paste0("DMR_", colnames(dmrDF)[8:ncol(dmrDF)])
cat(sprintf("Total %i unique genes\n",length(unique(dmrDF$gene))))
write.table(dmrDF, file=sprintf("%s/Sarropoulos_RL_DMR_overlap_inferredEP_upregGenes_oneTSS.txt", outDir), 
    sep="\t", row.names=FALSE, quote=FALSE)



cat(" Running gene set enrichment analysis\n")
fg_genes <- unique(dmrDF$gene)
bg_genes <- unique(inferredEP$gene)
cat(sprintf("%i FG genes and %i BG genes loaded.\n\n", 
    length(fg_genes), length(bg_genes)))
source("../FETHB2-FETHB3/gprofiler2_helpers.R")
    # run pathway enrichment analysis (from `gprofiler2_helpers.R`)
gost_res <- run_gost(
      query = fg_genes,
      organism = "hsapiens",
      #organism =  "gp__OUFl_gpIE_RyE",
      significant = TRUE,
      sources = c("GO:BP","GO:CC","REAC","WP"),
      evcodes = TRUE,
      correction_method = "fdr",
      custom_bg = bg_genes,
      filename = file.path(outDir, "enriched_pathways")
    )


cat("Now running FIMO on DMR-overlapping enhancer sequences\n")
dmr_seq <- getSeq(BSgenome.Hsapiens.UCSC.hg38, 
    names=dmrDF$chr_enh, 
    start=dmrDF$start_enh, 
    end=dmrDF$end_enh
)
names(dmr_seq) <- sprintf("%s:%s-%s", dmrDF$chr_enh, dmrDF$start_enh, dmrDF$end_enh)
fimoIn <- sprintf("%s/inferredEP_DMRs.fa", outDir)
writeXStringSet(dmr_seq, filepath=fimoIn)

fimoRes <- runFimo(
    sequences = fimoIn,
    motifs = tf_db,
    meme_path = meme_path,
    outdir = sprintf("%s/FIMO_motif_hits", outDir)
)

# create a table of the FIMO hits, and annotate which ones are in DMRs that overlap inferred E-P connections linked to upregulated genes, and which TFs are neurodev or MB TFs.
inferredEP_DMRs_GR <- makeGRangesFromDataFrame(dmrDF, 
    seqnames.field="chr_enh", start.field="start_enh", end.field="end_enh")
ol <- findOverlaps(fimoRes, inferredEP_DMRs_GR)
fimoDF <- as.data.frame(fimoRes)
colnames(fimoDF) <- paste0("FIMO_", colnames(fimoDF))
bothDF <- cbind(dmrDF[subjectHits(ol),],fimoDF[queryHits(ol),])
bothDF <- bothDF[!duplicated(bothDF),]
write.table(bothDF, file=sprintf("%s/Sarropoulos_RL_DMR_overlap_inferredEP_upregGenes_FIMOhits.txt", outDir), 
    sep="\t", row.names=FALSE, quote=FALSE)

dpos <- regexpr("\\.", bothDF$FIMO_motif_id)
bothDF$TF <- substr(bothDF$FIMO_motif_id, 1, dpos-1)
write.table(bothDF, file=sprintf("%s/Sarropoulos_RL_DMR_overlap_inferredEP_upregGenes_FIMOhits_annotated.txt", outDir), 
    sep="\t", row.names=FALSE, quote=FALSE)

# write a SIF file for Cytoscape. First column should be the dmr name (chr:start-end), second column should be "linked_to", third column should be the gene name.
#pexp <- -log10(fimoDF$FIMO_pvalue); qtl90 <- which(pexp >= quantile(pexp, 0.9))
#tmp <- bothDF[qtl90,]

cat("Reading genes of interest\n")
neurodev_genes <- get_neurodevGenes()
g34_genes <- get_g34genes()  

ol_neurodev <- unique(intersect(bothDF$gene, neurodev_genes))
ol_g34 <- unique(intersect(bothDF$gene, g34_genes))
cat(sprintf("Of the target genes in the inferred E-P connections that overlap DMRs, %s are neurodev genes and %s are MB genes\n", 
    prettyNum(length(ol_neurodev), big.mark = ","), 
    prettyNum(length(ol_g34), big.mark = ",")
))

allgenes <- union(neurodev_genes, g34_genes)
tmp <- bothDF[which(bothDF$gene %in% allgenes | bothDF$TF %in% allgenes),]

pexp <- -log10(tmp$FIMO_pvalue); qtl90 <- which(pexp >= quantile(pexp, 0.9))
tmp <- tmp[qtl90,]
sifDF <- data.frame(
    "TF" = tmp$TF, #sprintf("%s:%s-%s", dmrDF$chr, dmrDF$start, dmrDF$end),
    "linked_to" = "linked_to",
    "gene" = tmp$gene
)
sifDF <- sifDF[!duplicated(sifDF),]
cat(sprintf("Total %s unique TF-gene interactions\n", prettyNum(nrow(sifDF), big.mark = ",")))
write.table(sifDF, file=sprintf("%s/Sarropoulos_RL_DMR_overlap_inferredEP_upregGenes_NeurodevG34.sif", outDir), sep="\t",
    row.names=FALSE, quote=FALSE, col.names=FALSE)

# create a data.frame of all the genes in the inferred E-P links, and annotate which ones are upregulated in the RL, which ones are neurodev genes, and which ones are MB genes.
all_genes <- union(bothDF$gene, bothDF$TF)
# create a single column whose status is "neurodev_gene", "mb_gene", "both", or "neither"
gene_df <- data.frame(
    "gene" = all_genes,
    "upregulated_in_RL" = all_genes %in% upreg_genes_hgnc,
    "neurodev_gene" = all_genes %in% neurodev_genes,
    "mb_gene" = all_genes %in% g34_genes,
    "status" = ifelse(all_genes %in% neurodev_genes & all_genes %in% g34_genes, "both", 
        ifelse(all_genes %in% neurodev_genes, "neurodev_gene", 
            ifelse(all_genes %in% g34_genes, "mb_gene", "neither")))
)
write.table(gene_df, file=sprintf("%s/Sarropoulos_RL_inferredEP_genes_annotation.txt", outDir), sep="\t", row.names=FALSE, quote=FALSE)

OTX2_loc <- bothDF[which(bothDF$gene == "OTX2"),]
OTX2_gr <- GRanges(OTX2_loc$chr_enh[1], 
    IRanges(min(OTX2_loc$start_enh), max(OTX2_loc$end_prom)))
gene_anno <- rtracklayer::readGFF(geneFile)
gene_anno <- subset(gene_anno, gene_type %in% "protein_coding")
gene_anno$symbol <- gene_anno$gene_name
gene_anno$transcript <- gene_anno$transcript_id
gene_anno$gene <- gene_anno$gene_id
gene_anno$chromosome <- gene_anno$seqid

tmp <- bothDF[which(bothDF$gene == "OTX2"),]
OTX2_conns <- data.frame( 
    Peak1 = sprintf("%s-%s-%s", tmp$chr_enh, tmp$start_enh, tmp$end_enh),
    Peak2 = sprintf("%s-%s-%s", tmp$chr_prom, tmp$start_prom, tmp$end_prom),
    coaccess=0.3 # dummy value to plot all
)
OTX2_conns <- OTX2_conns[!duplicated(OTX2_conns),]

pdf(sprintf("%s/OTX2_Cicero_connections.pdf",outDir), width=6, height=3)
plot_connections(OTX2_conns, 
    "chr14", 56702558, 56819077, #OTX2 region
    gene_model = gene_anno, 
    coaccess_cutoff = 0.25, 
    collapseTranscripts = "gene",
)
dev.off()


}, error=function(ex){
    print(ex)
}, finally={
    sink(NULL)
})