# Integrate Sarropoulos et al. ATAC and RNA data for mid-gestation samples to infer enhancer-gene links.

rm(list=ls())
library(Signac)
library(Seurat)
library(ggplot2)
library(EnsDb.Hsapiens.v86)
library(BSgenome.Hsapiens.UCSC.hg38)

library(future)
plan("multicore", workers = 6)
options(future.globals.maxSize = 50 * 1024 ^ 3)

# Steps for RNA-ATAC integration were taken from the following sources:
# https://satijalab.org/seurat/articles/seurat5_atacseq_integration_vignette
# https://github.com/stuart-lab/signac/discussions/466

# Files generated by Sarropoulous_ATAC.R code.
atacFile <- "/home/rstudio/isilon/private/projects/FetalHindbrain/Sarropoulos2026/260402/Sarropoulos_ATAC_Seurat.rds"
rnaFile <- "/home/rstudio/isilon/private/projects/FetalHindbrain/Sarropoulos2026/260402/Sarropoulos_RNA_Seurat.rds"
fragDir <- "/home/rstudio/isilon/src/neurodev-genomics/scMultiome/Sarropoulos_2026"

geneFile <- "/home/rstudio/isilon/private/projects/FetalHindbrain/anno/gencode.v44.basic.annotation.gtf"
chromSizes <- "/home/rstudio/isilon/private/projects/FetalHindbrain/anno/hg38.chrom.sizes"

CPG_DMR_FILE <- "/home/rstudio/isilon/private/projects/FetalHindbrain/EMseq_FETHB3/output/downstream/EMseq_FETHB2-FETHB3/CpG/DMRs/CTsnv_excluded/withoutBatchCorrection/240711/DMRs.csv"

outDir <- "/home/rstudio/isilon/private/projects/FetalHindbrain/Sarropoulos2026"
outDir <- sprintf("%s/%s_Integrate", outDir, format(Sys.Date(),"%y%m%d"))
if (!file.exists(outDir)) dir.create(outDir, recursive = FALSE)

logFile <- sprintf("%s/%s_Integrate.log", outDir, format(Sys.Date(),"%y%m%d"))
sink(logFile, split = TRUE)

tryCatch({

    # annotate ATAC peaks with gene names.
cat("reading Sarropoulos ATAC Seurat object\n")
t0 <- Sys.time()
atac <- readRDS(atacFile)
print(Sys.time()-t0)
cat(sprintf("Sarropoulos ATAC: %i cells, %i features\n", ncol(atac), nrow(atac)))

cat("Reading Sarropoulos RNA Seurat object\n")
t0 <- Sys.time()
rna <- readRDS(rnaFile)
print(Sys.time()-t0)
rna <- FindVariableFeatures(rna, nfeatures = 10000)

cat("Adding fragment files to ATAC object\n")
fList <- list()
x <- colnames(atac)
for (fName in list.files(fragDir, pattern = "_renamed.tsv.gz$", full.names = TRUE)){
    cat(sprintf("Adding fragment file: %s\n", basename(fName)))
    sampName <- substr(basename(fName), 1, regexpr("_", basename(fName)))
    fList[[fName]] <- CreateFragmentObject(
        path = fName,
        cells = x[grepl(sampName, x)],
        validate.fragments = TRUE
    )
}
Fragments(atac) <- fList

cat("Annotating ATAC peaks with gene names\n")
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v86)
ucsc.levels <- stringr::str_replace(string=paste("chr",seqlevels(annotations),sep=""), pattern="chrMT", replacement="chrM")
seqlevels(annotations) <- ucsc.levels
genome(annotations) <- "hg38"
annotations$gene_symbol <- annotations$gene_name
annotations$gene_name <- annotations$gene_id # needed to match ensembl IDs in RNA assay. otherwise you get a "genes not found" error.
Annotation(atac) <- annotations

cat("Creating gene activity matrix with top 10K genes\n")
genes.to.use <- VariableFeatures(rna)
gene.activities <- GeneActivity(atac, features = genes.to.use)
atac[["ACTIVITY"]] <- CreateAssayObject(counts = gene.activities)

# normalize gene activities
DefaultAssay(atac) <- "ACTIVITY"
atac <- NormalizeData(atac)
atac <- ScaleData(atac, features = rownames(atac))

cat("Finding transfer anchors for integration\n")
transfer.anchors <- FindTransferAnchors(
    reference = rna, query = atac, features = genes.to.use,
    reference.assay = "originalexp", query.assay = "ACTIVITY", reduction = "cca")

cat("Impute RNA for the ATACseq dataset\n")
refdata <- GetAssayData(rna, assay = "originalexp", slot = "data")[genes.to.use,]
imputation <- TransferData(
    anchorset = transfer.anchors, 
    refdata = refdata, 
    weight.reduction = atac[["lsi"]],
    dims = 2:30
)
atac[["RNA"]] <- imputation
atac$orig.ident <- "ATAC"
rna$orig.ident <- "RNA"

coembed <- merge(x = rna, y = atac)
coembed <- ScaleData(coembed, features = genes.to.use, do.scale = FALSE)
coembed <- RunPCA(coembed, features = genes.to.use, verbose = FALSE)
coembed <- RunUMAP(coembed, dims = 1:30)

p <- DimPlot(coembed, group.by = c("orig.ident", "precisest_label"), reduction = "umap", label = FALSE, ncol = 2) 
p <- p + ggtitle("Sarropoulos RNA-ATAC co-embedding")
ggsave(sprintf("%s/RNA_ATAC_coembedding.png", outDir), plot=p, width=22, height=8)

browser()

cat("Running LinkPeaks\n")
md <- coembed[[]]
cats <- c("progenitor_RL","GCP/UBCP")
cat(sprintf("Filtering for cells in the category: { %s }\n",
    paste(cats, collapse=", ")))

idx <- union(which(md$precisest_label %in% cats), 
    which(md$rna_precisest_label %in% cats))
cat(sprintf("Total %i cells in selected categories\n", length(idx)))

rlonly <- subset(coembed, cells = rownames(md)[idx])
DefaultAssay(rlonly) <- "peaks"
# first compute the GC content for each peak
rlonly <- RegionStats(rlonly, genome = BSgenome.Hsapiens.UCSC.hg38)
rlonly <- LinkPeaks(
  object = rlonly,
  peak.assay = "peaks",
  expression.assay = "RNA"
)

LinkPeaks_output <- Links(rlonly)
cat(sprintf("Covers %i unique genes\n", length(unique(LinkPeaks_output$gene))))
LinkPeaks_output$gene_symbol <- annotations$gene_symbol[match(LinkPeaks_output$gene, annotations$gene_name)]
save(LinkPeaks_output, file = sprintf("%s/LinkPeaks_%s_output.RData", outDir, 
paste(sub("\\/","_",cats), collapse="_")))

geneDF <- as.data.frame(genes)
geneDF$ensembl_id <- substr(geneDF$gene_id, 1, regexpr("\\.", geneDF$gene_id)-1)

geneSet <- c("WLS","MKI67","EOMES","RBFOX3")
ensID <- geneDF$ensembl_id[match(geneSet, geneDF$gene_name)]
p <- FeaturePlot(rna, features = ensID, reduction = "umap", label = FALSE)

s2e <- function(s){
    geneDF$ensembl_id[which(geneDF$gene_name == s)]
}

ggsave(p, filename = sprintf("%s/FeaturePlot_genes.png", outDir), width=12, height=8)
p <- DimPlot(rna, group.by = "precisest_label", reduction = "umap", label = FALSE) + ggtitle("Sarropoulos RNA UMAP")
ggsave(p, filename = sprintf("%s/RNA_UMAP.png", outDir), width=18, height=8)

# DimPlot but plotting just the progenitor_RL cluster
p <- DimPlot(rna, group.by = "precisest_label", reduction = "umap", label = FALSE) + 
    ggtitle("Sarropoulos RNA UMAP") + 
    theme(legend.position = "none") +
    geom_point(data=subset(rna, cells = rownames(rna)[rna$precisest_label == "progenitor_RL"])  , color="red", size=0.5)
ggsave(p, filename = sprintf("%s/RNA_UMAP_progenitor_RL.png", outDir), width=18, height=8)

# plot violinplot of MKI67 expression in the progenitor_RL cluster vs all other clusters
geneSet <- c("PAX6", "MKI67", "WLS", "EOMES", "RBFOX3")
for (g in geneSet){
    p <- VlnPlot(rna, features = s2e(g), group.by = "precisest_label", pt.size = 0.1) + ggtitle(sprintf("%s expression in Sarropoulos RNA data", g))
    p <- p + theme(legend.position = "none")
    ggsave(p, filename = sprintf("%s/%s_violin.png", outDir, g), width=16, height=8)
}

}, error = function(e) {
    cat("Error: ", conditionMessage(e), "\n")
}, finally = {
    sink()
})
