library(regioneR)
library(ggpubr) #ggarrange
library(rtracklayer)
library(doParallel)

#' get DMR overlap enrichment relative to length- and GC-matched reanges
#' @param pos (GRanges) query GRanges e.g., DMRs
#' @param tgtGR (GRanges) target GRanges e.g., HARs, enhancers, etc.,
#' @param numPerm (integer) number of permutations to test
#' @param tgtName (char) target name, prefixes output graphss
#' @param negDir (char) path to directory with bed files of null sets. If NULL, will be generated by this function
#' @param rngSeed (integer) RNG set seed for reproducibility
#' @param genome (BSgenome) should be *.masked genome.
#' @param outDir (char) path to output directory.
#' @param direction (char) direction of the one tail permutation, either gt or lt. The default is gt.
#' @return (list) 1) overlap_pos: number of overlaps in positive set
#' 2) overlap_negs: number of overlaps in null sets.
getGRanges_OLenrichment <- function(pos,tgtGR,numPerm,negDir=NULL, idxDir=NULL,
    tgtName="overlap",
    rngSeed=12345, genome=NULL,
    outDir=".", verbose=FALSE,
    direction=c("gt", "lt")
){
    set.seed(rngSeed) 

    direction <- match.arg(direction)
    cat(sprintf("Testing for %s overlap enrichment, direction=%s\n", tgtName, direction))

    if (is.null(negDir)) stop("provide negDir")
    if (!file.exists(negDir)){
        cat(sprintf("Getting null sequences for %i permutations\n", numPerm))
        t0 <- Sys.time()
        ###tryCatch({
        dir.create(negDir)
        negs <- getNullGRanges(
            pos=pos, 
            genome=genome, 
            numSets=numPerm,
            outDir=negDir
        )
        ###}, error=function(ex){
        ###    print(ex)
        ###    cat("removing negDir\n")
        ###    file.remove(negDir)
        ###}, finally= {
        ###    cat("Done generating null seqs.\n")
        ###})
        print(Sys.time()-t0)
    } else {
        if (verbose) cat(sprintf("neg ranges provided, just going to use those...\n"))
       # negs <- dir(path=negDir, pattern="neg")
       # negs <- negs[grep(".bed$",negs)]
       # negs <- sprintf("%s/%s",negDir,negs)
       # cat(sprintf("Found %i neg sets\n",length(negs)))
    }

    out <- plotGRanges_OLenrichment(pos, tgtGR, tgtName, negDir, idxDir)
    p       <- out$p
    nullol  <- out$nullol
    realol  <- out$realol
    numPerm <- length(nullol)

    pdf(sprintf("%s/%s_overlaps_realvsnull.pdf",outDir,tgtName))
    print(p)
    dev.off()

    cat(sprintf("Num. perm = %i\n", numPerm))
    cat(sprintf("%% overlap, real = %1.2f%%\n", realol))
    cat(sprintf(paste("%% overlap, ",
        "negative seqs = Median %1.2f%%, [%1.2f - %1.2f]\n",sep=""), 
        median(nullol), min(nullol), max(nullol)))
    
    # strict one tail 
    if (direction == "gt") {
      pval <- max(sum(nullol>=realol)/numPerm, 1/numPerm)
      cat(sprintf("Num null >= real overlaps = %i (p < %1.2e)\n", 
        sum(nullol>=realol), pval))      
    } else if (direction == "lt") {
      pval <- max(sum(nullol<=realol)/numPerm, 1/numPerm)
      cat(sprintf("Num null <= real overlaps = %i (p < %1.2e)\n", 
        sum(nullol<=realol), pval))  
    }

   return(list(overlap_pos=realol, overlap_negs=nullol, plot=p, pval = pval))
}

#' get DMR overlap enrichment relative to length- and GC-matched reanges
#' @param pos (GRanges) query/positive set of intervals e.g., DMRs
#' @param tgtGR (GRanges) target GRanges e.g., HARs, enhancers, etc.,
#' @param tgtName (char) target name, prefixes output graphss
#' @param negDir (char) path to directory with bed files of null sets. If NULL, will be generated by this function
#' @param idxDir (char) path to directory with matched indices of null sets. If NULL, will not be used
#' @param numCores (integer) num cores for parallel processing
#' @return (list) 
#' 1) p (ggplot2) Plot showing distribution of pct overlap of null sequences, with red line showing overlap in positive set.
#' 2) nullol (numeric) number of overlaps in null ranges
plotGRanges_OLenrichment <- function(pos, tgtGR, tgtName, negDir, idxDir, numCores=10L,verbose=FALSE) {
  if (verbose) cat("Plotting: Counting overlap of real vs null sets\n")
  negs <- dir(path=negDir, pattern="neg")
  negs <- negs[grep("(?<!unfiltered)\\.bed", negs, perl = TRUE)] # to use only filtered ones
  negs <- sprintf("%s/%s",negDir,negs)
  if (verbose) cat(sprintf("Found %i neg sets\n",length(negs)))

  getOverlap <- function(gr,gr2)  length(subsetByOverlaps(gr,gr2))/length(gr)

  cl <- makeCluster(numCores)
  registerDoParallel(cl)
   on.exit(stopCluster(cl))
  
  if (!is.null(idxDir)) {
    if (verbose) cat("Matching null seqs to positive seqs by CpG deciles...\n")

  }
  nullol <- foreach (k=seq(1,length(negs),10),.packages=c("rtracklayer")) %dopar% {  
    cur <- c()
    maxK <- min(k+9, length(negs))
    for (m in k:maxK){
     # print(m)
      neg <- import(negs[m])
      if (!is.null(idxDir)) {
        idxFile <- sprintf("%s/matched_indices_neg%d.txt", idxDir, m)
        if (file.exists(idxFile)) {
          match_idx <- read.table(idxFile, header=FALSE)[,1]  
          neg <- neg[match_idx]
        } else {
          cat(sprintf("Warning: idx file %s not found. Using all neg seqs.\n", idxFile))
        }
      }
     # cat(sprintf("Processing neg set %d/%d\n", m, length(negs)))
     # cat(sprintf("\t%d neg seqs\n", length(neg)))
  
      #if (length(negs) <=10) plist[[k]] <- compareGR(pos,neg)
      cur <- c(cur, getOverlap(neg, tgtGR))
    }
    return(cur)
  }
  nullol <- unlist(nullol)

  nullol <- nullol*100
  realol <- getOverlap(pos,tgtGR)*100
  numPerm <- length(negs)
  if (verbose) cat("Plotting results\n")
  perms <- data.frame(iter=c(1:numPerm),ol=nullol)
  p <- ggplot(perms, aes(x=nullol))+ geom_density() +
    geom_vline(xintercept=realol,color="red", size = 1) +
    xlab("Percent ranges overlap") + 
    ggtitle(sprintf("Pct. overlaps,  %s (N=%i permutations)", tgtName, numPerm)) +
    theme(axis.text=element_text(size=18))
  
  return(list(p=p,nullol=nullol,realol=realol))
}

#' creates a set of negative sequences to test overlap enrichment
#' matches for length and GC content. by default excludes all non-standard chromosomes. i.e., keeps only chr1-22,XYM.
#' @param pos (GRanges) positive set
#' @param numSets (integer) num negative sets to generate; usually num. permutations
#' @param genome (BSgenome) if NULL, assumes is hg38
#' @param outDir (char) path to output directory all bed/fasta files need to be stored
#' @param numCores (integer) num cores for parallel processing
#' @param filterBismapMappable (logical) if TRUE only keep seqs overlapping
#' Bismap mappable regions
#' @import doParallel
#' @import gkmSVM
#' @return (char) vector of length "numSets" with path to bed files containing negative sets.
getNullGRanges <- function(pos, numSets,genome=NULL, outDir=".", numCores=10L,
  filterBismapMappable=TRUE) {
    library(gkmSVM)
    library(doParallel)

    cl <- makeCluster(numCores)
    registerDoParallel(cl)
     on.exit(stopCluster(cl))

    if (is.null(genome)){
        genome <- BSgenome.Hsapiens.UCSC.hg38.masked
        genome <- keepStandardChroms(genome) # remove alternate chroms
    }

    if (filterBismapMappable) {
        bismap <- getBismapMappable()
      }

    posF <- sprintf("%s/pos.bed",outDir)
    export(pos,posF)

    foreach (k=1:numSets, .packages=c("gkmSVM","rtracklayer","GenomicRanges")) %dopar% {
      cur <- sprintf("%s/neg%i.bed",outDir, k)
      neg <- genNullSeqs(
        posF, 
        genome=genome,
        outputPosFastaFN=sprintf("%s/pos%i.fa",outDir, k),
        outputBedFN=cur,
        outputNegFastaFN=sprintf("%s/neg%i.fa", outDir, k),
        batchsize=15000
      )

      if (filterBismapMappable) {
        negFile <- sub(".fa$",".bed",neg)
        negGR <- import(negFile)

        # only keep those completely overlapping bismark mappable regions
        negGR <- subsetByOverlaps(negGR, bismap)
        hits <- findOverlaps(negGR, bismap)
        hits <- hits[unique(queryHits(hits))] #sometimes 1 range overlaps 
                                              #+ and - Bismap
        overlaps <- IRanges::pintersect(
          negGR[queryHits(hits)], 
          bismap[subjectHits(hits)]
        )
        # only keep perfect overlaps
        percentOverlap <- width(overlaps) / width(negGR[queryHits(hits)])
        negGR <- negGR[queryHits(hits)[which(percentOverlap>0.9)]]
        
        file.rename(negFile, sub(".bed",".unfiltered.bed",negFile))
        export(negGR,con=negFile)
      }
    }
    outF <- sprintf("neg%i.bed", 1:numSets)
    return(paste0(outDir,"/",outF))
}

#' plot jaccard index of null GRanges. do they substantially overlap?
getJaccard_NullRanges <- function(negDir, subsample=10) {
  negs <- dir(path=negDir, pattern="neg")
  negs <- negs[grep(".bed$",negs)]
  negs <- sprintf("%s/%s",negDir,negs)

  negs <- sample(negs, subsample,F)
  n <- length(negs)

  comb <- matrix(0,nrow=n,ncol=n)
  jacc <- function(x,y) sum(width(IRanges::intersect(x,y)))/sum(width(IRanges::union(x,y)))
  for (i in 1:(n-1))
    for (j in i:n) {
         gr1 <- import(negs[i])
         gr2 <- import(negs[j])
         comb[i,j] <- jacc(gr1,gr2)
    }
  comb
}

#' return data.frame of overlapping coordinates between gr1 and gr2
#' @param gr1 (GRanges) interval 1
#' @param gr2 (GRanges) interval 2
#' @return (data.frame) concatenated coordinates and metadata columns of 
#' gr1 and gr2 
getDF_GRoverlap <- function(gr1,gr2) {
  ol <- findOverlaps(gr1,gr2)
  df <-  data.frame(gr1[queryHits(ol)])
  colnames(df) <- paste("gr1",colnames(df),sep=".")
  df2 <- data.frame(gr2[subjectHits(ol)])
  colnames(df2) <- paste("gr2",colnames(df2),sep=".")

  df <- cbind(df,df2)
  chrom <- as.numeric(sub("chr","", df$gr1.seqnames)); 
  if(any(df$gr1.seqnames %in% "chrX")) 
    chrom[which(df$gr1.seqnames %in% "chrX")] <- 23
  if(any(df$gr1.seqnames %in% "chrY")) 
    chrom[which(df$gr1.seqnames %in% "chrY")] <- 24
  if(any(df$gr1.seqnames %in% "chrM")) 
    chrom[which(df$gr1.seqnames %in% "chrM")] <- 25
    
  df <- df[order(chrom,df$gr1.start),]

  df
}

#' compare length and GC content of negative sequences, and generate
#' bed file for UCSC exploration.
compareNull2RealSeqs <- function(pos,negDir,subsample=10L, 
  outFile="compareNegs.pdf",outBed="negs.bed") {
  negs <- dir(path=negDir, pattern="neg")
  negs <- negs[grep(".bed$",negs)]
  negs <- sprintf("%s/%s",negDir,negs)

  negs <- sample(negs, subsample,F)
  pdf(outFile)
  neg_GR <- GRanges()
  for (cur in negs) {
    neg <- import.bed(cur)
    p <- compareGR(pos,neg)
    print(p)
    neg_GR <- c(neg_GR,neg)
  } 
  dev.off()
  export.bed(neg_GR, con=outBed)
  browser()
}

#' plot violin of negative overlaps compared to real DMRs
#' 
#' @param pos (GRanges) positive intervals (e.g., DMRs)
#' @param tgtList (list of GRanges)  ranges to test for overlap with pos
#' (e.g., enhancers, CTCF-binding sites, disease SVs, etc.,)
#' @param negDir (char) path to directory with null genomic intervals
#' @param levels (char) a vector that filter and order the bars
#' @return (list)
#' p (ggplot): plot of violins, data points and p-values
#' neg (data.frame): "pctoverlap" and "set"
#' pos (data.frame): "pctoverlap","set","pval"
plotViolins_OLenrichment <- function(pos, tgtList, negDir, levels = NULL) {
  out <- list()
  neg <- list()
  real <- list()
  lor <- list() 
  for (nm in names(tgtList)) {
     out[[nm]] <- plotGRanges_OLenrichment(pos, tgtList[[nm]], nm, negDir)
     neg[[nm]] <- cbind(out[[nm]]$nullol, nm)
     numPerm <- length(out[[nm]]$nullol)
      pval <- max(sum(out[[nm]]$nullol>=out[[nm]]$realol)/numPerm, 1/numPerm)

     tmp <- log2(out[[nm]]$realol/out[[nm]]$nullol)
     if (any(is.infinite(tmp))) tmp[which(is.infinite(tmp))] <- 16 

     real[[nm]] <- cbind(out[[nm]]$realol,nm,pval)
     lor[[nm]] <- cbind(tmp, nm)
     
  }
  negs <- do.call("rbind",lor)
  negs <- as.data.frame(negs)
  negs[,1] <- as.numeric(negs[,1])
  colnames(negs) <- c("logOR","set")

  pos <- do.call("rbind",real)
  pos <- as.data.frame(pos)
  pos[,1] <- as.numeric(pos[,1])
  pos[,3] <- as.numeric(pos[,3])
  colnames(pos) <- c("pctoverlap","set","pval")

  data_summary <- function(data, varname, groupnames){
    require(plyr)
    summary_func <- function(x, col){
      c(mean = mean(x[[col]], na.rm=TRUE),
        sd = sd(x[[col]], na.rm=TRUE))
    }
    data_sum<-ddply(data, groupnames, .fun=summary_func,
                    varname)
    data_sum <- plyr::rename(data_sum, c("mean" = varname))
   return(data_sum)
  }

  df2 <- data_summary(negs, varname="logOR",groupnames="set")
  tmp <- df2
  
  if (! is.null(levels)) {
    df2 <- df2[df2$set %in% levels,]
    df2$set <- factor(df2$set, levels = levels)
  } else {
    df2$set <- as.factor(df2$set)
  }
 
  p <- ggplot(df2, aes(x=set, y=logOR),color="grey50") +
    geom_bar(stat="identity",color="black",position=position_dodge()) +
    geom_errorbar(aes(ymin=logOR,ymax=logOR+sd), width=0.1, 
        position=position_dodge(0.9)) +
    theme_minimal()
  p <- p + ylab(sprintf("log(FC) (mean+/-SD, %i permutations)", 
        nrow(lor[[1]])))
  ##p <- p + geom_violin(data=negs,aes(factor(set),pctoverlap)) +
  ##  geom_boxplot(data=negs,aes(factor(set),pctoverlap),width=0.05)
  ##p <- 
  ##p <- p + geom_point(data=pos,aes(factor(set),pctoverlap),col="red")
  ##p <- p + ylab("% overlap")
  #p <- p + annotate(geom="text", x=1:nrow(pos), y=maxval, 
   # label=sprintf("p < %1.2f", pos$pval))
  
  p <- p + theme(axis.text=element_text(size=18), axis.text.x = element_text(angle = 45, hjust = 1))
  #p <- p + ylim(0,max(c(negs[,1],pos[,1]))*1.15)

  return(list(p=p, neg=negs, real=pos, df2=tmp))
}

#' check overlap of null ranges with BSseq-mappable regions
#'
#' @param negDir (char) path to dir with null sequences
#' @param subsample (integer) how many neg seq sets to sample?
checkOLwithMappability <- function(negDir,subsample=10L){
  source("utils.R")
  mGR <- getBismapMappable()

  negs <- dir(path=negDir, pattern="neg")
  negs <- negs[grep(".bed$",negs)]
  negs <- sprintf("%s/%s",negDir,negs)

  browser()

  negs <- sample(negs, subsample,F)
  for (cur in negs) {
    neg <- import.bed(cur)
    browser()
  } 
}

#' get Bismap S100 mappability
#' 
#' @return (GRanges) union of S100+ C2T and S100- G2A
getBismapMappable <- function(){
    mFile <- "/home/rstudio/isilon/src/ucsc-goldenpath/hg38/k100.C2T-Converted.bb"
    gr <- import(mFile)
    mFile2 <- "/home/rstudio/isilon/src/ucsc-goldenpath/hg38/k100.G2A-Converted.bb"
    gr2 <- import(mFile2)
 
    gr <- IRanges::union(gr,gr2)
    strand(gr) <- "*"
    gr
}


##testNullSeqs_bismapMappable <- function(){
##  source("utils.R")
##  library(BSgenome.Hsapiens.UCSC.hg38.masked)
##
##  projectRoot <- "/home/rstudio/isilon/private/projects/FetalHindbrain/EMseq_FETHB3/output/downstream/EMseq_FETHB2-FETHB3/CpG/DMRs/CTsnv_excluded/withoutBatchCorrection/240522"
##  maskFile <- "/home/rstudio/isilon/src/ucsc-goldenpath/hg38/masks/BISMAP_mask.txt.gz"
##
##  dmr <- getDMRs(projectRoot)
##  export(dmr, "pos.bed")
##    
##  hg38 <- BSgenome.Hsapiens.UCSC.hg38.masked
##  msk <- read.delim(maskFile,h=F,sep="\t")
##  msk <- GRanges(msk[,1],IRanges(msk[,2],msk[,3]))
##  source("genNullSeqs_BismapMappable.R")
##  cat("about to call func\n")
##  neg <- genNullSeqs_BismapMappable(
##        "pos.bed", 
##        genome=hg38,
##        outputPosFastaFN="pos1.bed",
##        outputBedFN="neg1.bed",
##        outputNegFastaFN="neg1.fa",
##        batchsize=10000,
##        bismapMask=msk
##  )
## }
