# get statistics for trimmed regions for the publication
rm(list=ls())
library(ggplot2)
library(GenomicRanges)
library(UpSetR)

inFile <- "/home/rstudio/isilon/private/projects/FetalHindbrain/EMseq_FETHB3/output/downstream/EMseq_FETHB2-FETHB3/CpG/DMRs/CTsnv_excluded/withoutBatchCorrection/240711/oligoDesign/trimmed_targets_240731.tsv"

  # RL active genes
  RL_ACTIVE_GENES <- "/home/rstudio/isilon/private/projects/FetalHindbrain/anno/Hendrikse2022_RL_activeGenes"

dt <- format(Sys.Date(),"%y%m%d")

outDir <- sprintf("%s/stats/",dirname(inFile))
outDir <- sprintf("%s/%s", outDir, dt)
if (!dir.exists(outDir)) {
  dir.create(outDir, recursive = TRUE)
}

rankedFile <- sprintf("%s/targetRanking_240731.tsv", dirname(inFile))
oligoSummaryFile <- sprintf("%s/crsAnnotate/250605/oligo_summary_250605.tsv", dirname(inFile))

dat <- read.table(inFile, header = TRUE, sep = "\t", stringsAsFactors = FALSE)
cat(sprintf("Total number of trimmed targets: %d\n", nrow(dat)))

cat("width distribution\n")
print(summary(dat$end-dat$start+1))

cat("source\n")
print(table(dat$source,useNA="always"))

cat("Reading ranked targets from file\n")
ranked <- read.table(rankedFile, header = TRUE, sep = "\t", stringsAsFactors = FALSE)

# plot violin plot of ranked scores
# add sample size beneath each violin
p <- ggplot(ranked, aes(x = source, y = score)) +
  geom_violin() + geom_boxplot(width = 0.05, fill = "white", outlier.shape = NA) +
  theme_minimal() +
  labs(title = "Ranked Scores by Source", x = "Source", y = "Score") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    EnvStats::stat_n_text(size=4)
ggsave(sprintf("%s/ranked_scores_violin_plot.pdf", outDir), plot = p, width = 8, height = 6)

cat("Focusing on DMRs overlapping fetal CB H3K27ac peaks\n")
dmr_fetCBenh <- dat[grep("fetalCbEnh",dat$source),]
cat(sprintf("Number of regions overlapping fetal CB H3K27ac peaks: %d\n", nrow(dmr_fetCBenh)))

# file of JASPAR TFBS overlaps with the DMRs that overlap fetal CB H3K27ac peaks
# only. Generated by getJasparTFBS_forTopTargets.sh
jasparOL <- sprintf("%s/../jaspar_overlaps.bed", outDir)
tfbs <- read.table(jasparOL, header = FALSE, sep = "\t", stringsAsFactors = FALSE)
cat(sprintf("Read %i JASPAR TFBS overlaps with DMRs\n", nrow(tfbs)))
tfbs_nondup <- tfbs[!duplicated(tfbs[,7:10]),]
cat(sprintf("After removing duplicates, %i JASPAR TFBS overlaps with DMRs\n", nrow(tfbs_nondup)))

ame <- "/home/rstudio/isilon/private/projects/FetalHindbrain/EMseq_FETHB3/output/downstream/EMseq_FETHB2-FETHB3/CpG/DMRs/CTsnv_excluded/withoutBatchCorrection/240711/SVZ_diff_hypo_AME_activeInRL_HOCOMOCOv12_240712/ame.tsv"
ame_dat <- read.table(ame, header = TRUE, sep = "\t", stringsAsFactors = FALSE)
dpos <- regexpr("\\.", ame_dat$motif_ID)
tf <- substr(ame_dat$motif_ID, 1,dpos-1)
cat(sprintf("Found %i TFs in AME results\n", length(tf)))
genes2keep <- tf

# filter JASPAR TFBS overlaps for RL active genes
tfbs_nondup <- tfbs_nondup[tfbs_nondup[,7] %in% genes2keep,]
cat(sprintf("After filtering for RL active genes, %i JASPAR TFBS overlaps with DMRs\n", nrow(tfbs_nondup)))


# count frequency of each TF, sort decreasing. Plot a barplot of the top 20 TFs.
tf_freq <- table(tfbs_nondup[,7])
tf_freq <- sort(tf_freq, decreasing = TRUE)
top_tf <- head(tf_freq, 30)
cat("Top 30 TFs in JASPAR TFBS overlaps with DMRs:\n")
print(top_tf)   
# plot barplot of top 20 TFs, plot in descending order of frequency. plot as 
# horizontal barplot with TFs on y-axis and frequency on x-axis.
top_tf <- as.data.frame(top_tf)
p <- ggplot(top_tf, aes(x = reorder(Var1, Freq), y = Freq)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    labs(title = "Top 30 TF binding sites in DMRs overlapping fetal CB H3K27ac peaks",
         x = "TF", y = "Number of TF binding sites in hit loci") +
    theme_minimal(base_size = 20)
ggsave(sprintf("%s/top_30_TFs_in_JASPAR_TFBS_overlaps_with_DMRs.pdf", outDir), plot = p, width = 8, height = 9)


cat("Reading oligo summary from file\n")
oligos <- read.table(oligoSummaryFile, header = TRUE, sep = "\t", stringsAsFactors = FALSE)

cat("Keep the ones overlapping dmr_fetCBenh\n")
oligos_GR <- GRanges(
    seqnames = oligos$seqnames,
    ranges = IRanges(start = oligos$start, end = oligos$end),
    strand = oligos$strand,
    name=oligos$id
)
# write bed file of the oligos
oligos_bed <- sprintf("%s/oligos.bed", outDir)
write.table(as.data.frame(oligos_GR), oligos_bed,
            col.names = FALSE, row.names = FALSE, quote = FALSE, sep = "\t"
)


dmr_fetCBenh_GR <- GRanges(
    seqnames = dmr_fetCBenh$seqnames,
    ranges = IRanges(start = dmr_fetCBenh$start, end = dmr_fetCBenh$end),
    strand = dmr_fetCBenh$strand
)

dat_GR <- GRanges(
    seqnames = dat$seqnames,
    ranges = IRanges(start = dat$start, end = dat$end),
    strand = dat$strand
)
x <- subsetByOverlaps(oligos_GR, dat_GR)
y <- subsetByOverlaps(oligos_GR, dmr_fetCBenh_GR)

oligos2 <- subset(oligos, id %in% y$name)
cols2show <- c("ol_feCBk27ac", "ol_feCBk27ac_summit",
                    "N2_N3_k27ac",
                    "isNeurodev",
                    "isG34MB",
                    "G34_mutated",
                    "ol_hars")

outFile <- sprintf("%s/oligo_summary_upSet_%s.pdf", outDir, dt)
pdf(outFile,width=10,height=6)
upset(as.data.frame(oligos2), 
      sets = cols2show,
      order.by = "freq",
      text.scale = 1.6, point.size = 3,
      sets.bar.color = c("#f8101b", "#f8101b","#fece2f","#fece2f",
                         "skyblue", "grey25", "#8e529e")
      )
dev.off()

# write the oligos2 to a file
outFile <- sprintf("%s/oligos_dmr_fetCBenhoverlap_%s.tsv", outDir, dt)
write.table(oligos2, outFile, 
            col.names = TRUE, row.names = FALSE, quote = FALSE, sep = "\t")

# plot a barplot of the top 20 nearestGenes
nearestGenes <- table(oligos2$nearestGene)
nearestGenes <- sort(nearestGenes, decreasing = TRUE)
top_nearestGenes <- head(nearestGenes, 20)
cat("Top 20 nearest genes in oligos:\n")
print(top_nearestGenes)
top_nearestGenes <- as.data.frame(top_nearestGenes)
p <- ggplot(top_nearestGenes, aes(x = reorder(Var1, Freq), y = Freq)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    labs(title = "Top 20 nearest genes in oligos",
         x = "Nearest Gene", y = "Number of Oligos") +
    theme_minimal(base_size = 20)
ggsave(sprintf("%s/top_20_nearest_genes_in_oligos.pdf", outDir), plot = p, width = 8, height = 9)

# print table of nearestGene for isNeurodev > 0
oligos_neurodev <- oligos2[oligos2$isNeurodev > 0,]
cat(sprintf("Number of oligos with isNeurodev > 0: %d\n", nrow(oligos_neurodev)))
tbl <- table(oligos_neurodev$nearestGene)
tbl <- sort(tbl, decreasing = TRUE)
cat("Table of nearest genes for oligos with isNeurodev > 0:\n")
print(tbl)

# print table of nearestGene for isG34 > 0
oligos_g34 <- oligos2[oligos2$isG34 > 0,]
cat(sprintf("Number of oligos with isG34 > 0: %d\n", nrow(oligos_g34)))
tbl_g34 <- table(oligos_g34$nearestGene)
tbl_g34 <- sort(tbl_g34, decreasing = TRUE)
cat("Table of nearest genes for oligos with isG34 > 0:\n")
print(tbl_g34)



# print out which are Group 3 / 4 driver genes
#neurodev <- get_neurodevGenes()
#mb <- et_g34genes()

